AIM-Harvard/pyradiomics

- radiomics/shape.py
This fixes an incorrectly hardcoded label that causes the calculation of features for labels != 1 to fail.
@JoostJM, unfortunately, I can't mention the whole team as suggested in the contribution guidelines.
> fix incorrectly hardcoded label when calculating volume

- radiomics/glcm.py
Wrong axis in `numpy.delete` caused the wrong dimension to be deleted from the `sumP_glcm` and a subsequent broadcast error between `sumP_glcm` and `P_glcm`.
Additionally, rename `sumGlcm` to `sumP_glcm` for consistency.
> Fix bug in GLCM

- requirements.txt
For integration with slicer, revert minimum required numpy version to 1.9.2. This is the version of numpy currently distributed with slicer, so if pyradiomics is installed to slicer as part of an extension module, it does not cause the installed numpy for slicer to be changed.
> Revert required numpy version

- bin/Notebooks/helloFeatureClass.ipynb
- bin/Notebooks/helloRadiomics.ipynb
- bin/helloFeatureClass.py
- bin/helloRadiomics.py
- docs/usage.rst
- radiomics/scripts/commandline.py
- radiomics/scripts/commandlinebatch.py
- setup.py
Rename the scripts to pyradiomics and pyradiomicsbatch (easy to remeber, but unique to package, for use in the commandline). Additionally, move them to separate folder in the package, and add them to the setup script so the CLI gets distributed with the installation, not just the git repo.
Additionally, add the use of these scripts to the `Usage` section of the documentation and adapt this section further to represent the more standard use of the toolbox, including interactive extraction using the `featureextractor` module.
Finally, adapt the examples in the bin folder to make use of the example data stored in the repository, this removes the need to install the example data when pyradiomics is installed.
> Add CLI scripts to setup

- radiomics/imageoperations.py
Due to some slicing errors, the wavelet filter resulted in a 90deg rotation and a mirroring along one axis. This resulted in that the labelmaps did not align with the ROI anymore, causing the wavelet features to be incorrectly calculated.
This PR addresses this error by recoding the slicing during wavelet decomposition. Results have been checked visually. I'll add some examples later.
> Fix incorrect slicing during application of wavelet filter

- radiomics/scripts/commandline.py
- radiomics/scripts/commandlinebatch.py
PyKwalify needs the parameter file to be passed as a string of the path, it does not accept an open file.
This caused the parameter file to be always ignored
> Fix type of optional parameter file in scripts

- README.md
- bin/Notebooks/PyRadiomics Example.ipynb
- docs/index.rst
- docs/usage.rst
Add a link to the pyradiomics webpage containing the instruction video to the README.
Additionally, embed the video in the usage section of the documentation, and running the usage example section.
Finally, include the python notebook used in the instruction video in pyradiomics/bin/Notebooks to enable hands-on testing
> Add links to the instruction video

- radiomics/__init__.py
- radiomics/featureextractor.py
- tests/test_docstrings.py
Move the `getFeatureClasses` and `getInputImages` out of the RadiomicsFeaturesExtractor class and to the radiomics namespace.
This makes these functions more globally available (as it is also used in the testing, which does not necessarily use the featureextractor).
Additionally, add new parameter, "additionalInfo" (Boolean) to control wheter or not to append the extra information on the extraction to the output. This additional information is provided by the generalinfo.py module.
> Move getFeatureClasses and getInputImages to radiomics namespace

- .flake8
- bin/addClassToBaseline.py
- bin/batchExamples/DatasetHierarchyReader.py
- bin/batchExamples/GenerateInputCSV_Datasethierarchy.py
- bin/batchExamples/GenerateInputCSV_Filename.py
- bin/batchExamples/batchprocessing.py
- bin/helloFeatureClass.py
- bin/helloRadiomics.py
- bin/helloResampling.py
- data/schemaFuncs.py
- radiomics/__init__.py
- radiomics/base.py
- radiomics/featureextractor.py
- radiomics/firstorder.py
- radiomics/generalinfo.py
- radiomics/glcm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/imageoperations.py
- radiomics/scripts/commandline.py
- radiomics/scripts/commandlinebatch.py
- radiomics/shape.py
- requirements-dev.txt
- setup.py
- tests/testUtils.py
- tests/test_docstrings.py
- tests/test_features.py
The style "appnexus" is used, it allows to  group import per PEP8
recommendations [1], while keeping the project specific imports last.
[1] https://www.python.org/dev/peps/pep-0008/#imports
> STYL: Fix import orders and enable flake8-import-order plugin

- circle.yml
This commit improves the fix originally introduced in de8ee88 (ci:
manylinux: Avoid sdist failure with workaround for distutils/setuptools
issue)
Reported-by: Joost van Griethuysen <j.v.griethuysen@nki.nl>
> ci: circleci: Do not fail if venv symlink is nonexistent

- tests/testUtils.py
This commit partially reverts commit d84c793 (STYL: testUtils: Improve
test outputs) and restore the sorting of columns written into the
CSV file.
Considering that data are organized using "featureClassName + featureName"
instead of just "featureName", information will remain consistently organized.
Suggested-by: Joost van Griethuysen <j.v.griethuysen@nki.nl>
> STYL: testUtils: Restore header sorting in test output

- data/schemaFuncs.py
`schemaFuncs.py` reflected the old implementation of `getFeatureClasses`, where it was implemented in `featureextractor`. As of 4771963, `getFeatureClasses` is implemented directly in the radiomics namespace. Update `schemaFuncs.py` accordingly.
> Fix getFeatureClasses() in schemaFuncs.py

- data/paramSchema.yaml
- radiomics/featureextractor.py
- radiomics/imageoperations.py
Optionally normalize gray value intensities before any resampling or filters are applied. Image is normalized on all gray values (not just those in the ROI). Disabled by default. Controlled by 3 new params (`normalize`, `normalizeScale` and `removeOutliers`).
> Implement normalization function in imageoperations

- radiomics/scripts/commandlinebatch.py
In python 3.x (tested 3.4) featureVector.keys() and
featureVector.values() don’t return a sequence expected in
writer.writerow() causing the error:
writer.writerow(featureVector.keys())
_csv.Error: sequence expected
writer.writerow(featureVector.values())
_csv.Error: sequence expected
> Fix pyradiomicsbatch error with python 3

- radiomics/featureextractor.py
When segmentation is passed as a SimpleITK image, the second check erroneously checks the imageFilePath instead of the maskFilePath for being an SimpleITK Image. This causes a bug when the image is supplied as a file location and the mask as an image.
Addtionally, add some checks to ensure image and mask are loaded before attempting to process further.
> BUG: Fix error when mask is passed as SimpleITK image

- bin/addClassToBaseline.py
- tests/test_features.py
In `addClassToBaseline`, code was not python 3 compatible. This was mainly due to a call to keys(), which in python 2 returns a list, but in python 3 returns an iterator.
> Further improve python 3 compatibility.

- requirements.txt
To build the documentation, both sphinx and the read the docs theme is necessary, but the latter was not specified in the requirements.
> Add sphinx_rtd_theme to requirements

- radiomics/base.py
- radiomics/featureextractor.py
- radiomics/glcm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
Add additional parameters to optionally force texture calculation to 2D. This is enabled by setting parameter `force2Dextraction` to True. Then, all angles moving across 'slices' are removed. The dimension which specifies the slice is defined in `force2Ddimension`. For example, if enabled and dimension is 0, texture is extracted only in the xy-plane (with dimension 0 specifying the 'z' dimension as slice-dimension). Forced 2D extraction is switched off by default.
Additionally, enable specifying custom distances between center voxel and neighbors. These distances are specified in the `distances` parameter as a list of integers. By default `disances = [1]`.
> Implement forced 2D texture extraction.

- radiomics/imageoperations.py
When checking if the ROI physical space is contained within the image physical space, direction is not taken into account when comparing in the physical space. Therefore, instead of bringing both the ROI and image bounds to the physical space, bring the ROI bounds first to the physical space and then to the image coordinate space. Then, compare those bounds with the minimum (always [-0.5, -0.5, -0.5]) and the maximum (image.GetSize() - 0.5) image bounds.
Additionally, add a tolerance to prevent machine precision errors (set at 1e-3).
> BUG: Error in geometry check during resampling

- radiomics/glrlm.py
Every voxel in the ROI is considered once per angle in GLRLM.
When weighting is applied in GLRLM, Np has to be corrected, as all angles are combined into one matrix, which mean Np has to reflect the number of voxels assessed (equals number of voxels in ROI * number of times each voxel is assessed).
> BUG: Correct Np when weighting is applied

- Dockerfile
This is initial version of the Dockerfile for pyradiomics, it is functional and can be accessed from Docker Hub with `docker pull fedorov/pyradiomics`. The approach follows Dockerfile as done in http://github.com/qiicr/dcmqi, in turn derived from the work by @thewtex in https://blog.kitware.com/how-to-build-distributable-c-executables-for-linux-with-docker/.
Let's discuss how to move forward with this, but from my discussions within QIN and ITCR, it will be extremely helpful for us to provide this docker image to facilitate participation in the community activities.
Things remaining to do:
> WIP: Add Dockerfile

- docs/installation.rst
Set up developer mode so cmatrices shared library is accessible.
Addresses [issue #244](https://github.com/Radiomics/pyradiomics/issues/244)
> Add extra install step

- bin/Notebooks/PyRadiomics Example.ipynb
- bin/Notebooks/helloFeatureClass.ipynb
- bin/Notebooks/helloRadiomics.ipynb
- bin/helloFeatureClass.py
- bin/helloRadiomics.py
- radiomics/__init__.py
This function is available in the radiomics namespace and takes the test case name as an argument. Optionally the location of the repository can also be specified, in which case the test files of the repository are used.
If test files cannot be found, the are downloaded from github and stored in a temporary folder.
This function returns a tuple of 2 strings representing the paths to the (downloaded) image and segmentation files.
TODO:
> Add function to get test case

- bin/batchExamples/GenerateInputCSV_Datasethierarchy.py
- bin/batchExamples/GenerateInputCSV_Filename.py
Update scripts for generating input CSV to reflect recent changes made to the expected format for input CSV.
> Update CSV Generators

- docs/installation.rst
Wheels are now available on PyPI for all supported architectures.
Fixes #247
> docs/installation: Remove SimpleITK workaround

- radiomics/glrlm.py
Correction of a i that should be a j in the SRE formula in the documentation.
> STYLE: Correction of the Short Run Emphasis documentation

- radiomics/firstorder.py
- radiomics/glcm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/shape.py
For some features the formula would return NaN in specific cases (e.g. a flat region). Document and return predefined values in these cases.
> Define return values for 0-division errors etc

- CHANGES.rst
- radiomics/shape.py
- radiomics/src/_cmatrices.c
- radiomics/src/_cshape.c
- radiomics/src/cmatrices.c
- radiomics/src/cmatrices.h
- radiomics/src/cshape.c
- radiomics/src/cshape.h
Enhance C extension algorithm for calculating GLSZM. Instead of searching over entire image for voxels to process when growing a region, instantiate a stack (max size equal to number of voxels) to hold indices for voxels that have to be processed for the current region.
When an unprocessed voxel, belonging to the ROI is found, a region is started by pushing the index of that voxels to the stack. Then a loop is started where the last added voxel in the stack is popped and its neighbours are checked. If unprocessed and belonging to the same region (same gray level), indices for those voxels are also pushed to the stack. The loop then runs until stack is exhausted (i.e. no new neighbours available, indicating the region is complete). The number of loops are counted and are equal to the size …
> Enhance C GLSZM

- CHANGES.rst
- bin/addClassToBaseline.py
- examples/helloFeatureClass.py
- notebooks/helloFeatureClass.ipynb
- radiomics/featureextractor.py
- radiomics/imageoperations.py
- tests/testUtils.py
This resolves #259
In the situation when the mask was corrected to compensate for the differences
between the image and mask geometry, the updated mask was not propagated to be
used for feature calculation.
> BUG: use resampled mask for analysis

- CHANGES.rst
- radiomics/glcm.py
To make GLCM symmetrical, the python code performed an inplace addition: `P_glcm += numpy.transpose(P_glcm, (1, 0, 2))`. However, when the matrix exceeds a certain size, this produces buggy behaviour, where for some elements, the calculated value equals `P_glcm += P_glcm + numpy.transpose(P_glcm, (1, 0, 2))`. This is caused by the fact that numpy.transpose returns a *view*, and not a copy of the array. Then, if the additions have to be processed in multiple chunks, the addition will become erroneous.
Use `numpy.copy` to get a transposed copy of the GLCM and not just a view of the GLCM.
> Fix bug when creating symmetrical GLCM

- CHANGES.rst
- docs/usage.rst
- examples/batchProcessingWithPandas.py
- examples/batchprocessing.py
- radiomics/scripts/commandlinebatch.py
Add functionality to allow users to specify different labels for different combinations in the input file for batchprocessing.
This is achieved through an additonal (optional) column `Label`. Integer values in this column then take precedence over any other form
of label customization (e.g. specifying the label on the command line or in the parameter file).
> Add case-specific labels in batchprocessing

- CHANGES.rst
- radiomics/shape.py
The eigenvalue decomposition calculation does not account for non-consecutive voxels in a line (along x dimension), causing the calculated values for the principal moments to be erroneous when a lesion has 'holes' in it. Furthermore, it assumes that all voxels on line x = i have identical y and z coordinates, but this is not necessarily the case.
> Replace SimpleITK's eigenvalue decomposition with a python one

- CHANGES.rst
- radiomics/glcm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- tests/test_cmatrices.py
Before computing features, remove unused rows and columns from the texture matrices and update the i and j vectors accordingly.
This reduces the size of the matrices, thereby both reducing the computation time (especially for very large segmentations with many empty rows/columns) and reducing the memory requirements.
> Remove empty row column texture

- radiomics/__init__.py
Currently,  PyRadiomics contains one circular import: `__init__.py` imports `base`, while `base` imports `radiomics` (`__init__.py`). However, base is only needed for the inheritance check in `getFeatureClasses`, change this to allow removal of the circular import.
While circular imports are allowed in python, then can cause unexpected behavior/bugs, and can mask an underlying bug preventing the import of a class (which is subsequently reported as a "cannont import name" error, instead of the actual bug preventing the import).
> Remove circular import

- CHANGES.rst
- LICENSE.txt
- README.md
- docs/index.rst
Addresses #268
Change the license to 3-clause BSD
Question: should there be a explicit statement "Not intended for clinical use" and if so, where should it go?
Possibilities:
- Extra clause in the license
- Statement at the top of the documentation
- Statement at the top of ReadMe.md
- Disclaimer in the log. (as a warning, and as such, will also be part of the output to the command window in default mode).
> Update license to 3-clause BSD

- radiomics/imageoperations.py
Hi guys,
I think the PR is self-explanatory. The if had no influence at all.
Cheers,
Fabian
Cc: @Radiomics/developers
> BUG: outlier removal not working

- Dockerfile
- notebooks/FeatureVisualization.ipynb
- notebooks/FeatureVisualizationWithClustering.ipynb
- radiomics/__init__.py
In python 3, the function `urlretrieve` is moved. Prevent incompatibility by using implementation in `six.moves`.
Affects the function to get a test case and the feature visualization notebooks.
Fixes #278
> Fix python3 incompatibility when getting a test case

- .circleci/config.yml
- Dockerfile
- notebooks/FeatureVisualization.ipynb
- notebooks/FeatureVisualizationWithClustering.ipynb
- notebooks/FilteringEffects.ipynb
- notebooks/RadiomicsExample.ipynb
See also [#433](https://github.com/jupyter/docker-stacks/pull/433) on jupyter/docker-stack.
Python 2 support is now removed from jupyter/datascience-notebook. Update dockerfile and config.yml to install python2 kernel manually.
> Fix missing python 2 environment

- radiomics/imageoperations.py
Related to #279
Document necessity of providing sigma values in a warning box. (now both in documentation of customization and in documentation of `GetLoG()` (function defining Laplacian of Gaussian filter).
> Make sigma documentation more clear

- radiomics/__init__.py
- radiomics/base.py
- radiomics/featureextractor.py
- radiomics/firstorder.py
- radiomics/glcm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/shape.py
Groups together common functions and splits assigning passed variables (such as `inputImage` and `inputMask`) and feature class percalculation (such as calculating the texture matrix), which enables customized initialization, such as in  `shape.py`.
Additionally, renamed matrixCoordinates to ROICoordinates, and moved assignment of the progress reporter to `__init__.py` (therefore only needing 1 call to a global function from the `base.py` module)
> Revise style in base initialization

- CHANGES.rst
- docs/customization.rst
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
When resampling, allow the output spacing for any dimension to be set to 0 (the parameter 'resampledPixelSpacing' still needs to be a sequence of 3 elements, but the value of any element can be 0). Doing so will enable 'preserving' the original spacing, as 0 values are replaced with the spacing for that dimension as it is in the original (non-resampled) mask. This way, it is possible to only resample in-plane (by setting the out-of-plane output spacing to 0).
Additionally, move the check between original and resampled spacing to after the size check (no resampling over dimensions for which bounding box size = 1) and build in a tolerance (1e-5 + 1e-8 * abs(resampledspacing)).
Finally, fix data type for resampled spacing in the validation schema for parameter files (change from integer to …
> Allow a 0 value for output spacing when resampling

- docs/customization.rst
- radiomics/featureextractor.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
Add functionality to resegment the mask prior to calculation of features (ony applies to firstorder / texture, no resegmentation possible prior to shape feature calculation). Introduces new parameter `resegmentRange`, a list of 2 floats which define the lower and upper threshold, respectively. Values outside the range specified are removed from the mask. After successful resegmentation, the resultant mask is rechecked to ensure it is still valid (using function `imageoperations.checkMask()`). A value of None (the default value) for the parameter `resegmentRange` disables resegmentation.
> Add optional resegmentation of mask

- radiomics/featureextractor.py
- radiomics/scripts/commandlinebatch.py
Add additional checks to ensure required columns are present and have a value for each case. If columns are missing, log an error and exit. If cells in required column have missing values (empty strings), log an error and skip to next case.
Also update the image and mask filepath if the path is relative, as it is assumed to be relative to the input file, not the current working directory.
Finally replace `os.path.exists` with `os.path.isfile` in `featureextractor.py`, as a directory is also an existing path, but should not be used during attempt to load using SimpleITK.
> Add additional checks to batch processing script

- examples/batchprocessing_parallel.py
Add an example of how to extract features using parallel threading (1 thread per case). Assumes similar input and produces similar output as `batchprocessing.py`, with the addition of two additional predifined, but optional, columns; "Patient" and "Reader".
Fixes #282 
> Add parallel batch processing example

- docs/customization.rst
- radiomics/base.py
Clarify that variables mentioned in the base class are variables instantiated by the base class, not possible settings for customization (also add redirect to customization documentation).
Update the documentation to reflect changes made to the structure of the base class, more specifically the initialization of a feature class.
Add documentation for the "Label" parameter to the customization documentation.
> Update documentation in base.py

- README.md
- appveyor.yml
- docs/developers.rst
- docs/faq.rst
- radiomics/__init__.py
- setup.py
When using PyRadiomics in 32 bits architecture, memory errors can arise when extracting large masks, or many small ones (see also #303).
Therefore, remove support for 32 bits architecture by raising an exception when trying to install PyRadiomics on 32 bits architecture.
Update documentation accordingly.
Reformat `setup.py` script to adhere to editorconfig settings
cc @Radiomics/developers, @michaelschwier
> Remove 32 bit support

- docs/customization.rst
- examples/exampleSettings/exampleMR_NoResampling.yaml
- radiomics/featureextractor.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
When resampling is enabled, image and mask are pre-cropped onto the bounding box (with additional padding). This speeds up the resampling process and the application of filters. Moreover, it can significantly reduce the memory footprint of the extraction, especially when the images are large, but contain only small ROIs.
Add functionality to also pre-crop the image when no resampling is applied. This way, the advantages when applying filters on a pre-cropped image and mask are also available when extracting without resampling.
Similar as pre-cropping when resampling, additional padding is available (parameter `padDistance`), which is ensure to not exceed the original image bounds.
> Add pre-cropping

- radiomics/gldm.py
- tests/testUtils.py
In full-python calculation of the GLDM matrix, calculation would fail when label != 1. Update GLDM to also work with different mask values.
Fix an additional bug in testUtils, where the Label value stored in the baseline was not passed to the checkMask function when loading a test case.
> Fix incorrect usage of self.maskArray

- docs/faq.rst
Add a FAQ explaining why pyradiomics only allows the specification of a fixed bin width, and not a fixed bin count.
> Add explanation on enforcing a bin width

- radiomics/imageoperations.py
Update coefficients to use `max(|x|)`, instead of `max(x)` (use the absolute values). This prevents invalid calculation, as `max(x)` can be negative (impossible sqrt in square filter). Furthermore, this defines the range to be scaled to the largest difference from 0, instead of just the maximum value (which can yield very different ranges).
> Change calculation of filter correction coefficients

- radiomics/imageoperations.py
PyWavelets package supports applying wavelets sequentially along multiple axes, therefore there is no need for reslicing the (partially filtered) data using python functions. This reduces a lot of complexity in the code and also includes a higher performance of the filter.
Additionally, allow for 2D application of wavelets when `force2D` is set to `True`, where no wavelet will be applied along the `force2Ddimension`.
CC @Radiomics/developers
> Simplify Wavelet filter function

- docs/customization.rst
- radiomics/featureextractor.py
Add a function (`LoadJSONParams`) in the featureextractor, which accepts a JSON formatted string. This string will then be validated similar to a parameter file and if successful, used to customize the extraction.
Additionally, change the documentation in the `Customize the extraction` section to enhance readability.
cc: @Radiomics/developers
> Add json configuration

- radiomics/generalinfo.py
Add versions of SimpleITK, Numpy and PyWavelet to the additional info output. PyRadiomics uses these 3 packages to process the images and calculate the features.
Fixes #341.
> DOCS: Add version of packages used in feature calculation

- docs/installation.rst
- radiomics/imageoperations.py
Add documentation with formulas defining the LoG filter.
> DOCS: Add formula for LoG

- radiomics/imageoperations.py
The resizing in `_swt3`, which is called by `getWaveletImage` to extend images to ensure image dims are multiples of 2, causes images to be scrambled, because numpy's `resize` simply adds zeros at the end of the buffer and changes the shape of the array (see [here](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.resize.html), esp. example 3).
Hence for enlarging we need to use `numpy.pad` and for shrinking back we need to use slicing (see fixed code).
This causes the wavelet results to be wrong for all images/ROIs with an odd dimension (actually for only odd z it might not be, because in this case the resize "accidentally" has the expected behavior).
All the above insights and the fixed code is courtesy of Jan Moltz/Fraunhofer MEVIS, who tracked this bug down.
To …
> BUG: Fixed resizing for wavelet filtering (resizing was scrambling image)

- CHANGES.rst
- radiomics/shape.py
If the segmentation in the dataset represents a 2D segmentation, the smallest of the 3 eigenvectors should be 0.
But because a transform to physical coordinates (taking into account rotation and scaling), this can actually compute very small (~1e-16) negative numbers.
This in turn causes an error in numpy.sqrt. This commit implements a 3-fold fix.
1) Because we do not need the eigen vectors, we can also calculate the eigenvalues using just the scaled coordinates, without rotation. In case of a 2D segmentation, this then results in correct calculation of 0 for the smallest eigen value.
2) After computation of eigen values. They are checked if they are negative, but > -1e-10. If that is the case, a warning is logged and they are rounded to 0.
3) Add additional checks to ensure the …
> BUG: Fix machine precision errors in eigen value calculation

- docs/customization.rst
- docs/index.rst
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
Returns an image with the gradient magnitude as voxel value.
Adds parameter `gradientUseSpacing`, which controls whether or not to take image spacing into account when computing the gradient.
> Add the Gradient Magnitude image filter.

- docs/customization.rst
- docs/developers.rst
- docs/features.rst
- docs/index.rst
- examples/helloFeatureClass.py
- notebooks/helloFeatureClass.ipynb
- radiomics/featureextractor.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
Requires `skimage` to function. `skimage` is not added to the requirements and only imported when the function is called. If the package is unavailable, a warning is logged and no image is yielded (does not crash the extraction, but no features for LBP are calculated)
> Add Local Binary Pattern Image Filter

- radiomics/schemas/paramSchema.yaml
- radiomics/schemas/schemaFuncs.py
Before, available filters were hard coded in the `paramSchema.yaml`, requiring the developer to add any new filters explicitly. Change this to use a schema validation rule which checks against the result of `getImageTypes`, which dynamically enumerates the available filters.
Additionally, by applying a regex matching rule that matches any key, the validation rule to test the custom settings is retained.
> Update the validation rule for image types

- radiomics/glcm.py
- radiomics/gldm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/ngtdm.py
- radiomics/shape.py
- radiomics/src/_cmatrices.c
- radiomics/src/_cshape.c
- radiomics/src/cmatrices.c
- radiomics/src/cmatrices.h
- radiomics/src/cshape.c
- radiomics/src/cshape.h
- tests/test_cmatrices.py
Various changes to the C extension with the aim of consistency between functions and the new implementation of C-generated angles.
- Move common functionality to different function (mainly various checks to ensure valid input data is provided)
- Make the texture functions more similar where possible (mainly use of `strides` and `size` arrays)
- Simplify surface area (removes a lot of unnecessary calculations)
- Remove deprecated numpy functionality and define constant to enforce no use of deprecated functionality in the future
- implement C function to generate angles and call this from the texture functions. Because sometimes the angles are used later on (e.g. matrix weighting), generated angles are also included in the return value; a tuple of `(matrix, angles)` is returned.
The …
> Update c functions

- docker/cli/Dockerfile
- radiomics/imageoperations.py
To enable local binary pattern 2D and 3D, scipy, scikit-image and trimesh are additionally required, but these are not mentioned in the requirements (to allow installing without these packages).
To enable these filters in the CLI-docker, add pip install lines for these packages to the dockerfile.
> BUG: Fix missing packages in Dockerfile

- radiomics/imageoperations.py
- radiomics/src/_cmatrices.c
When the GLCM is calculated in C, an array is generated of size Ng x Ng x Na (Ng = number of bins, Na = number of angles). If the number of bins exceeds 12852 with 13 angles, the resulting array has more than 2,147,483,648 elements, which in turn causes the index variable (int32) to overflow, crashing the python interpreter.
Seeing as generally ~100 bins are advised, limit the number of bins instead of using datatypes that can reach higher numbers. A maximum number of 7000 is chosen (allowing for a maximum of 43 angles in GLCM). If the number of bins exceeds this number, an error is raised.
Additionally, add a size check prior to instantiating the output arrays in C. If the size > 2147483648, throw an error.
Fix typo in error message when calculation of angles fails.
> ENH: Add check to prevent too many bins from being generated

- docs/customization.rst
- docs/faq.rst
- docs/usage.rst
- radiomics/base.py
- radiomics/featureextractor.py
- radiomics/firstorder.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
For extra compatibility allow user to extract using a fixed bincount. 
Include a warning when fixed bincount is used to show the recommendation for a fixed bin width.
See [this FAQ topic](http://pyradiomics.readthedocs.io/en/latest/faq.html#why-is-there-no-parameter-to-specify-a-fixed-bin-count) for more details.
> ENH: Add support for using a fixed bin count

- docs/faq.rst
- radiomics/imageoperations.py
- radiomics/src/_cmatrices.c
Check if Matrix arrays are allocated correctly
If size is too big or the computer is unable to allocate memory for the output texture matrices, the function (PyArray_SimpleNew) returns NULL. Check for this and throw a python runtime error if that is the case.
Replace the large number with `INT_MAX` in the size check for increased readability.
Finally, update the documentation by adding detailed description of the potential errors thrown by the C extension in the FAQ section.
> Revise bincount checks

- .circleci/config.yml
- .travis.yml
- MANIFEST.in
- appveyor.yml
- scikit-ci.yml
- setup.cfg
- setup.py
ENH: Add publishing to PyPi to continuous integration
Adds a deploy step for all 3 ci-servers used by pyradiomics (supporting Linux, Windows and Mac OSX).
The deployment step is only run for tagged releases, i.e. when a build is triggered for a tag.
Furthermore, this tag is checked against a regex expression, to restrict deployment only to releases (e.g. v1.0, v2.1.3) and/or release candidates (e.g. v1.0-rc1, v2.1.3-rc12).
Authentication to the PyPi server is done using (private) environment variables set in the accounts on the various CI-servers. These variables will be only available to builds on branches/tags in the repository that is linked to the CI-account (i.e. not available for forked builds).
Finally, the current deployment step publishes to the test server, rather than the live …
> Publish pypi

- radiomics/shape.py
Note that this issue has no effect on the calculation, but might be confusing to the developers,
and also might cause problems later in case those are reused in a feature where order matters.
Resolves #403
> ENH: fix the assigment of x and y pixel spacing

- docker/cli/Dockerfile
For the additional filters, PyRadiomics requires scikit-image, which in
turn requires matplotlib. To install this package, freetype and libpng
are needed. Install these as well.
> BUG: Fix missing requirements in docker CLI file

- radiomics/generalinfo.py
Add a general info feature that computes the center of mass of the current ROI.
Center of mass is computed in both continuous index coordinates (`getCenterOfMaskIndexValue`) and real-world coordinates (`getCenterOfMassValue`).
cc @Radiomics/developers, @salimkanoun
> Add center of mass (General Info)

- radiomics/featureextractor.py
- radiomics/generalinfo.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
In addition to the original mode (now default mode "absolute"), add new modes "relative" and "sigma", which allow for a dynamic threshold defined as either a threshold relative to the maximum value found in the ROI ("relative") or as a n * sigma difference from the mean ("sigma").
Additionally, it is now allowed to provide either 1 or 2 thresholds, where in case of 1 threshold it is interpreted as the lower threshold (i.e. retaining everything equal to or higher than that threshold).
In case the function fails, a ValueError is raised. The checks to determine the validity of the resegmented mask is not determined in this function, but is applied in the pipeline defined by featureextractor.
> Extend resegmenting functionality

- radiomics/featureextractor.py
- radiomics/generalinfo.py
When image and mask do not share an identical geometric space, the general info elements for ROI mean, minimum and maximum are incorrect. In case where the mask size does not match the image size, this even produces an error.
Therefore, do not include the image prior to the image and mask geometry are ensured to be the same (this is only the case for the original mask, as the next step is either resampling (forcing similar geometry) or checkMask (comparing/correcting geometry)).
Additionally, add spacing and size elements of the mask for comparison.
> BUG: Fix error in generation of provenance info with misaligned mask

- docs/customization.rst
- radiomics/featureextractor.py
- radiomics/schemas/paramSchema.yaml
Add new paramter `resegmentShape` to control this behaviour. This allows the user to also use the resegmented mask for shape calculation, e.g. in the usecase of PET, where a resegementation based on SUV may be performed (e.g. to obtain mean tumor volume).
Addtionally, update documentation to reflect new resegmentation modes.
> ENH: Allow to also use resegmented mask for shape calculation

- radiomics/scripts/__init__.py
- radiomics/scripts/segment.py
Implement thread-safe logging to a file by using a `QueueHandler` and `QueueListener` to process the log records intended for the logfile. This ensures only 1 thread is writing to the file, preventing corruption in case of collisions.
Additionally, improve the error catching code in the commandline script to allow for cancellation by the user (via `KeyboardInterrupt`/ `SystemExit` and in case of parallel processing; by calling `pool.terminate()`)
> Thread safe logging

- data/baseline/baseline_shape2D.csv
- radiomics/__init__.py
- radiomics/featureextractor.py
- radiomics/shape2D.py
- radiomics/src/_cshape.c
- radiomics/src/cshape.c
- radiomics/src/cshape.h
- tests/addTest.py
- tests/testUtils.py
Add a new featureclass implementing shape features describing a 2D shape.
This class can only be extracted if `force2D = True` and the size of the bounding box is 1 in the dimension specified by `force2Ddimension` (i.e. it must be a truly 2D segmentation)
This featureclass is therefore not enabled by default.
> Add 2D Shape features

- README.md
- docs/customization.rst
- docs/index.rst
- docs/usage.rst
- radiomics/featureextractor.py
- radiomics/scripts/__init__.py
- radiomics/scripts/segment.py
- radiomics/scripts/voxel.py
Update command line entry point to allow either segment- or voxel-based extraction.
Update documentation to detail usage of PyRadiomics in voxel-based extraction.
> Add voxel cli

- radiomics/featureextractor.py
- radiomics/firstorder.py
- radiomics/generalinfo.py
- radiomics/imageoperations.py
- radiomics/shape.py
- radiomics/shape2D.py
- radiomics/src/_cmatrices.c
- radiomics/src/cmatrices.c
- radiomics/src/cmatrices.h
Update C extensions to make extraction N-Dimensional
> Update c extensions

- examples/exampleSettings/exampleVoxel.yaml
- radiomics/base.py
- radiomics/featureextractor.py
- radiomics/firstorder.py
- radiomics/glcm.py
- radiomics/gldm.py
- radiomics/glrlm.py
- radiomics/glszm.py
- radiomics/ngtdm.py
- radiomics/schemas/paramSchema.yaml
- radiomics/src/_cmatrices.c
- radiomics/src/cmatrices.c
- radiomics/src/cmatrices.h
Builds on PR #463 by adding bounding-box constrained iteration in the C extensions.
This is then used to speed up and simplify voxel-based extraction:
- no need to iterate over the entire image, only the defined kernel
- no need to keep updating the mask array, kernel defined as combination of maskArray and bounding box in C (i.e. voxel index +/- kernelRadius in moving dimensions)
- allows vectorized feature calculation of multiple voxels
> Add bounding box iteration

- docs/usage.rst
- radiomics/featureextractor.py
- radiomics/imageoperations.py
- radiomics/schemas/paramSchema.yaml
- radiomics/scripts/segment.py
- radiomics/scripts/voxel.py
In the new version of Slicer, segmentation is done using Segmentation Objects, which allow for overlapping segmentation. When stored, these `.seg.nrrd` files can be read by SimpleITK as vector images. By extracting the nth index from the vector, a labelmap (3D volume) can be obtained representing the nth segement. To ensure correct functionality in the rest of PyRadiomics, all non-zero in the obtained mask are then set to the label value.
> Add support for overlapping masks / Slicer Segementation objects

- radiomics/src/cshape.c
In `cshape.c`, `v_max` would quickly overflow with big images resulting in messages like `RuntimeError: Calculation of Shape coefficients failed`. To mitigate this effect, this PR changes its type from `int` to `size_t` (usually `unsigned long`).
> BUG: Mitigate integer overflow

- examples/helloRadiomics.py
- radiomics/src/_cmatrices.c
- radiomics/src/cmatrices.c
Replace indexing using `int` data type by `size_t` and `intptr_t` datatype (depending on whether negative values are needed).
> BUG: Mitigate integer overflow in texture classes

- radiomics/imageoperations.py
If input image array has a dType with max-value smaller than the number of bins, an overflow can occur, causing invalid values and subsequent faillure of texture matrix calculation (e.g. values of '0' or negative values can be present, causing index errors).
To prevent this, ensure the output datatype is 'int', which has a large enough dynamic range to prevent overflow (if number of bins is larger than INT_MAX, the extraction will most likely fail anyway, due to size/memory issues).
> BUG: Force dType of discretized image array to int.

- docker/cli/Dockerfile
in 10fa9c8, Python version used in the CLI docker was updated to python 3.6.9. However, this resulted in docker using the `python` and `pip` commands to use the much older 2.6 installed in the base image.
Replace the commands by `python3` and `pip3` to use the newer version of python.
> BUG: Update docker CLI to use python 3.6.9

- docker/cli/Dockerfile
- labs/pyradiomics-dcm/Dockerfile
- labs/pyradiomics-dcm/pyradiomics-dcm.py
Add docker, based on PyRadiomics:CLI docker and latest QIICR/dcmqi docker image to containerize DICOM -> DICOM workflow
> Add Docker for PyRadiomics-dcm Labs

- radiomics/glcm.py
- radiomics/gldm.py
- radiomics/glrlm.py
- radiomics/glszm.py
`emptyGrayLevels` is used as integer indices to remove the gray levels from the matrix. However, in linux python 3.6 and 3.7, the datatype defaults to `int64`, which is rejected by python when trying to use this as an index. Therefore, for the datatype of `emptyGrayLevels` to `int`, preventing the `IndexError`.
Fixes #592
> Force emptyGrayLevels datatype to int

- radiomics/featureextractor.py
When instantiating the feature extractor with a path pointing to a parameter file, it should fail if the path fails to resolve to an existing file. If that is the case, raise an IOError.
Additionally, allow the path to be provided as a pathlib.PurePath (or subclass thereof).
Fixes #587.
> Fail if parameter file path is non-existent

- radiomics/src/cmatrices.c
"0" is an invalid value for gray level and causes an index error in the calculation of texture matrices (e.g. for GLSZM, correct index in matrix is calculated as (i, j) = (grayvalue - 1, region size), which in case of gray value 0 results in index -1, which is invalid).
In some case, this resulted in a graceful error where an IndexError is raised, but this is most likely because the datatype used for the index (`size_t`) does not allow for negative indices on some systems and therefore results in an overflow, which on the subsequent check is then indeed larger than the maximum allowed index (which is checked). In other cases, `size_t` datatype does allow for negative values and therefore passes the maximum index check and subsequently fails with a Process terminated.
Add an additional …
> BUG: Fail gracefully when grayvalue <= 0

- radiomics/__init__.py
- radiomics/base.py
Update base.py to add progress reporting when computing voxel batches. Uses `radiomics.getProgressReporter`, which should be set to something like `tqdm.tqdm` to work. Only shows progress bar when logging level is at least INFO (so not when WARNING or higher).
> ENH: Add optional progress reporting for voxel-based extraction

- radiomics/src/cmatrices.c
When calculating the GLSZM matrix, processed voxel indices are temporarily stored in the `processedStack`, and the current position in stored in `processed_idx`. To ensure no overflow errors occur, the `processed_idx` value is compared to the maximum size of `processedStack` (=equal to `Ns`) prior to pushing an index.
This index is used, and then increased, meaning that if it's value = Ns - 1, it is still valid (though the last index to be valid). However, the check compared value + 1 >= Ns, which would fail in this last case. Update the check to allow this value.
Fixes #615 and #617
> BUG: Fix out-of-range check in glszm C calculation

- examples/exampleSettings/MR_2D_extraction.yaml
In the example showing settings for 2D MR extraction, the setting `force2D` was missing. Add this setting with a value of `true` to ensure this example forces a 2D extraction.
@rcuocolo
> DOCS: Add force2D setting to example settings

- .travis.yml
Despite updates in #643, Travis CI still reports errors during testing.
This PR implements a further fix to the Travis CI Pipeline, by updating Brew before installing `gettext`.
> Travis CI Integration

- radiomics/imageoperations.py
If a mask contains only a single label, a ValueError is raised stating no labels are found in the mask. However, this error should only be raised if the only label found is '0'.
Fixes #658
> BUG: Allow specification of full mask.

- CHANGES.rst
- labs/pyradiomics-dcm/README.md
- labs/pyradiomics-dcm/pyradiomics-dcm.py
This PR exposes `geometryTrolerance` and `correctMask` extractor settings to the CLI of `pyradiomics-dcm` making it possible to process to process images that raise an `'Image/Mask geometry mismatch'` error.
The default parameters are the same as the default parameters in `sitk` and `pyradiomics`:
- `geometryTolerance` is [1e-6](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1ProcessObject.html#a61dc7bc36a573d0f4a133bca60ed598c)
- `correctMask` is [False](https://pyradiomics.readthedocs.io/en/latest/customization.html?highlight=correctMask#feature-extractor-level)
---
> Expose mask correction and geometry tolerance to the pyradiomics-dcm CLI

- docs/usage.rst
Updated the notebooks directory from `pyradiomics/examples/Notebooks` to `pyradiomics\notebooks` to match the repository current structure.
> DOCS: Update notebooks directory in usage docs

- examples/batchprocessing_parallel.py
In the example for parallel batch processing: If the user passes a label column in the input CSV, the fetched label does not get passed to the feature extractor. This leads to extracting features of the same label, even if different labels are provided in the CSV file.
The non-parallel versions already do this correctly.
> fix: label assignment for feature extraction

- radiomics/scripts/__init__.py
I recently found the SlicerRadiomics extension does not work in 3D Slicer and below is the issue that I decribed in.
https://github.com/AIM-Harvard/SlicerRadiomics/issues/80
I tried to modify the code with the help of @pieper :
1. Add the code below to the top of the file:
`from ruamel.yaml import YAML`
2. Add the code below before line 353:
`yaml = YAML(typ='safe', pure=True) `
3. Change what was in line 353 to:
`settingsSchema = yaml.load(schema)['mapping']['setting']['mapping']`
> SafeLoadRemove Error in Slicer

- radiomics/gldm.py
Fixed the formula for SDE calculation from GLDM. The present formula is actually for LGLE.
I also checked the formula against [IBSI documentation](https://arxiv.org/pdf/1612.07003) (Chapter 3.11.1).
> fix typo in gldm sde formula

- pyproject.toml
Testing has confirmed that python3.11 and 3.12 both cause segmentation faults when loading the locally built radiomics/src c-modules.
> COMP: Limit to environments of python3.9 and python3.10

- .flake8
- radiomics/__init__.py
- radiomics/_version.pyi
versioneer is no longer used for version management.     setuptools-scm is now used.
> Remove versioneer
