README.md, docs/index.rst
This PR adds a list of the main contributors and their affiliations to the Readme file and to the general documentation.
=> Add developers and affiliations

radiomics/glszm.py
=> Add some references in GLSZM

setup.py
Reflects more advanced status of the toolbox.
=> Update the classifiers in setup script

tests/testUtils.py
* Update feature name in testing output to reflect the feature class.
* write "N/A" string when no data can be found
* write csv as text file using `w` instead of `wb` (this should help with
the transition to py3)
=> STYL: testUtils: Improve test outputs

.circleci/config.yml, bin/Notebooks/PyRadiomics Example.ipynb
Accidentally removed "bin/Notebooks/PyRadiomics Example.ipynb", restoring.
=> Restore accidentally removed file

CHANGES.rst, CONTRIBUTING.md, docs/changes.rst, docs/faq.rst, docs/index.rst
Add CHANGES.rst containing the release notes of the different PyRadiomics versions.
Add changelog.rst to enable linking to the release notes when autogenerating the documentation.
=> Add changelog

radiomics/featureextractor.py
Provides prerequisite for https://github.com/Radiomics/SlicerRadiomics/pull/26
=> BUG: initialize inputImage from kwargs

examples/exampleSettings/Params.yaml, examples/exampleSettings/exampleCT.yaml, examples/exampleSettings/exampleMR_3mm.yaml, examples/exampleSettings/exampleMR_5mm.yaml, examples/exampleSettings/exampleMR_NoResampling.yaml
cc @Radiomics/developers 
Add example settings for different modalities as a starting point.
=> Add example settings

docs/features.rst, radiomics/firstorder.py, radiomics/glcm.py, radiomics/glrlm.py, radiomics/glszm.py, radiomics/imageoperations.py, radiomics/shape.py
Add a reference to the feature definitions by IBSI, and document where PyRadiomics features differ.
=> Add reference to IBSI feature definitions

notebooks/helloFeatureClass.ipynb, radiomics/shape.py
Self-explaining
Cc: @Radiomics/developers
=> Fixes typos

radiomics/featureextractor.py
When parameter validation fails, PyKwalify logs an error. However, by default, no handlers are configured (as pyradiomics defines it's handlers at the 'radiomics' level, not the root logger).
Check if either the root logger or PyKwalify has a logger handler configured. If not, add the first radiomics handler (the stream handler with output to stderr), so the error is logged if the parameter validation fails.
Fixes #304
cc @Radiomics/developers, @sunhuaiqiang
=> Add logger handler to pykwalify if none is defined

README.md
=> README: Improve badges layout

radiomics/scripts/commandline.py, radiomics/scripts/commandlinebatch.py
Add a command line argument to skip printing out features that compute a NaN.
Fixes #314
=> Add --skip-nans command line argument

.travis.yml
As suggested by @jcfr in https://github.com/Radiomics/pyradiomics/pull/332#issuecomment-356097814
=> BUG: add pip link

radiomics/imageoperations.py
I have just added some comments to the method _swt3 which is called inside the method getWaveletImage
=> -swt3 comments

radiomics/imageoperations.py
=> BUG: Fix an error in generating the approximation name for wavelet.

radiomics/glcm.py
Inverse Difference, Inverse Difference Moment, Inverse Difference Normalized, Inverse Difference Moment Normalized and Inverse Variance all use a |i=j| element, which is equal to the k_diff. This enables the use of p_x-y (`pxSuby`) and k_diff (`kValuesDiff`), which are precomputed in `_calculateCoefficients`. Note that for Inverse Variance, the first element (k = 0) is skipped, in accordance with the constraint of i not equal to j in the formula.
As `pxSuby` contains fewer elements and dimensions than `P_glcm`, replacing `P_glcm` by `pxSuby` and `numpy.abs(i-j)` by `kValuesDiff` simplifies the function, and less computations are required.
Update the feature formulas in the documentation accordingly.
The final calculated result should be identical (within machine precision), therefore the …
=> ENH: Simplify computation of various GLCM features

.circleci/config.yml, .travis.yml, appveyor.yml, conda/bld.bat, conda/build.sh, conda/configure_conda.bat, conda/configure_conda.sh, conda/meta.yaml
Add a conda recipe and update the Coninuous Integration scripts so, that upon a release, a distribution is also uploaded the the Radiomics channel on Anaconda.
Additionally, limit deployment steps so, that they are only run when built from the main repository (Radiomics/pyradiomics)
fixes #412
=> Publish conda

radiomics/scripts/__init__.py
Checks if passed settings are valid and if all file locations for input Image and Mask exist.
=> ENH: Implement input validation for PyRadiomics script

CONTRIBUTING.rst
Minor: fix 2 typos in the CONTRIBUTING.rst file which result in broken links to mailing list and issue tracker.
=> Fix 2 broken links in contrib file.

docs/usage.rst
print("Stored feature %s in %s" % (key, key + ".nrrd"))
=> finishing print

.circleci/config.yml, .travis.yml, appveyor.yml
Drop support for Python 3.4 (not maintained anymore since March 2019), add support for Python 3.7
=> Update ci python dists

radiomics/imageoperations.py
#544
cc: @Radiomics/developers
Note: Tests fail but I ran them on the current master branch and they fail as well
=> Fix resampling operation for 2d images

docs/customization.rst, examples/exampleSettings/MR_2D_extraction.yaml
Created example parameter file with comments specific for 2D MRI extraction.
=> 2D MRI extraction parameter file example

radiomics/ngtdm.py
=> DOCS: Fix typo in documentation of NGTDM

.travis.yml
Fixes the error thrown by travis CI about loading libintl, as suggested in https://github.com/scikit-build/cmake-python-distributions/pull/113.
=> BUG: Fix Travis CI bug

Dockerfile, docker/cli/Dockerfile
Update the Docker CLI file to fix the CMAKE repository url.
Remove the Python2 support in the Docker with the jupyter notebooks.
=> Update Docker files

radiomics/glszm.py
heterogeneneity to heterogeneity
=> fixed small typo in glszm.py

.github/workflows/ci.yml, .gitignore, README.md, pyproject.toml
Fix the versions of python3 and the python packages.
=> Set python version explicitly

.github/workflows/ci.yml, pyproject.toml, radiomics/src/_cmatrices.c, radiomics/src/_cshape.c
Minor cleanups to the c-code to remove support for python<3 and to address clang tidy warnings.
=> C code updates

radiomics/featureextractor.py
Replaces issue #847: added Dicom file reader
code updated to match current coding style formats.
=> ENH: If file path is directory, attempt to read dicom series

radiomics/glcm.py
Addresses issues identified in #883 to reduce the number of numpy copy and delete operations.  Re-implements issue #882.
=> PERF: Improve glcm performance
